### ISSUE TITLE
Allow passing Nomad CA Certs via environment variables

### ISSUE THREAD

**Issue by jvineet** [trivago/scalad#3]
### Issue

Our nomad servers are set up with TLS which requires the corresponding `Nomad CA Certs` to be able to make api calls successfully. Currently there isn't a way for scalad to communicate with nomad when it set up with TLS.

### Operating system and Environment details
`Ubuntu 16.04.6 LTS (Xenial Xerus)`

**Comment by jvineet** [comment]
I believe I don't have access to create a PR or push a feature branch but here is how we ended up bypassing the issue:
[1752e8e](https://github.com/zumper/scalad/pull/1/commits/1752e8e146a13b11e0a075d32eaed9f8a4370ebc)

**Comment by jrasell** [comment]
@jvineet just an FYI on this one as I noticed the PR; you can use the `DefaultConfig()` func of Nomads API package which will read all standard Nomad env-vars and populate a config.
